source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'thin' # annoying messagess off

# Authentication framework
gem 'devise'
# Omniauthable
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-gplus'

gem 'acts-as-taggable-on'
gem 'httparty'
gem 'twitter'
gem 'sidekiq'
gem 'oj'
gem 'oj_mimic_json'
gem 'js-routes'
gem 'whenever', require: false
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap', '~> 1.0'
gem 'nokogiri', '~> 1.6.3'
gem 'cancancan', '~> 1.9'

group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'meta_request'
end
