#
# do not move 'url_prefix' option to env variables, set it right here
# because it should be loaded on assets:precompile (it starts as a separate process), but not with server
# the rest environment variables are set with apache virtual host through SetEnv
#
development:
  secret_key_base: # put "rake secret" output here
  url_prefix: # read note above
  email:
    username:
    password:
  twitter:
    consumer:
      key:
      secret:
    access:
      key:
      secret:
  instagram:
    consumer:
      key:
      secret:
    access_token:
  tumblr:
    consumer:
      key:
      secret:
    access:
      key:
      secret:
  facebook:
    consumer:
      key:
      secret:
    app_access_token:
  google_plus:
    consumer:
      key:
      secret:
    app_access_token:
#-------------------------------------------------------------------------------
test:
  secret_key_base: # put "rake secret" output here
  url_prefix: # read note above
  email:
    username:
    password:
  twitter:
    consumer:
      key:
      secret:
    access:
      key:
      secret:
  instagram:
    consumer:
      key:
      secret:
    access_token:
  tumblr:
    consumer:
      key:
      secret:
    access:
      key:
      secret:
  facebook:
    consumer:
      key:
      secret:
    app_access_token:
  google_plus:
    consumer:
      key:
      secret:
    app_access_token:
#-------------------------------------------------------------------------------
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  url_prefix: # read note above
  email:
    username: <%= ENV['EMAIL_USERNAME'] %>
    password: <%= ENV['EMAIL_PASSWORD'] %>
  twitter:
    consumer:
      key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
      secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
    access:
      key: <%= ENV['TWITTER_ACCESS_KEY'] %>
      secret: <%= ENV['TWITTER_ACCESS_SECRET'] %>
  instagram:
    consumer:
      key: <%= ENV['INSTAGRAM_CONSUMER_KEY'] %>
      secret: <%= ENV['INSTAGRAM_CONSUMER_SECRET'] %>
    access_token: <%= ENV['INSTAGRAM_ACCESS_TOKEN'] %>
  tumblr:
    consumer:
      key: <%= ENV['TUMBLR_CONSUMER_KEY'] %>
      secret: <%= ENV['TUMBLR_CONSUMER_SECRET'] %>
    access:
      key: <%= ENV['TUMBLR_ACCESS_KEY'] %>
      secret: <%= ENV['TUMBLR_ACCESS_SECRET'] %>
  facebook:
    consumer:
      key: <%= ENV['FACEBOOK_CONSUMER_KEY'] %>
      secret: <%= ENV['FACEBOOK_CONSUMER_SECRET'] %>
    app_access_token: <%= ENV['FACEBOOK_APP_ACCESS_TOKEN'] %>
  google_plus:
    consumer:
      key: <%= ENV['GOOGLE_PLUS_CONSUMER_KEY'] %>
      secret: <%= ENV['GOOGLE_PLUS_CONSUMER_SECRET'] %>
    app_access_token: <%= ENV['GOOGLE_PLUS_APP_ACCESS_TOKEN'] %>